services:
  controller:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: controller
    command: ["python", "-u", "controller/controller.py"]
    ports: 
      - "50050:50050"
    volumes: 
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      SCALE_UP_THRESHOLD: "10"
      SCALE_DOWN_THRESHOLD: "2"
      NETWORK_NAME: "project3_net"
    networks: ["project3_net"]

  service-node-1:
    image: project3-image:latest
    command: ["python", "-u", "service/service.py"]
    environment:
      GRPC_SERVER_PORT: "50060"
    networks: ["project3_net"]

  storage-node-1:
    image: project3-image:latest
    command: ["python", "-u", "storage/storage_node.py"]
    environment:
      GRPC_SERVER_PORT: "50051"
    networks: ["project3_net"]

networks:
  project3_net:
    name: project3_net